# -*- coding: utf-8 -*-
"""2a-weatherstations.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HuaMW9m3l6mD-PxIltSvoKbd2pNhVvek

# Weather stations
Get list of relevant weather stations in Canada

* Inputs: 
 * Weather - Stations/station_inventory.csv
 * World Shapefile/World_Shapefile.zip
 * {province} Location/{province}_grid_system.csv.gz
* Outputs: {province}_grid_system_with_station.csv.gz
"""

# Imports
!pip install geopandas

import pandas as pd
import numpy as np
import geopandas as gpd
from geopandas import GeoDataFrame, plotting
from shapely.geometry import Point, Polygon, box, LineString
import matplotlib.pyplot as plt 
from descartes import PolygonPatch
import random
from google.colab import drive
import zipfile

# Mount Google Drive
drive.mount('/content/gdrive')
root_path = '/content/gdrive/My Drive/Capstone Public Folder/Data/'

province = 'AL'

# Read in data
stations = pd.read_csv(root_path + 'Weather - Stations/station_inventory.csv')

# Check data is read in
stations.head()

file_path = root_path + 'World Shapefile/World_Shapefile.zip'
with zipfile.ZipFile(file_path,"r") as zip_ref:
  zip_ref.extractall('.')

# Check the column names
list(stations)

# Drop irrelevant columns
stations.drop([
 'WMO ID',
 'TC ID',
 #'Latitude (Decimal Degrees)',
 #'Longitude (Decimal Degrees)',
 'HLY First Year',
 'HLY Last Year',
 'DLY First Year',
 'DLY Last Year',
 'MLY First Year',
 'MLY Last Year'
], axis=1, inplace=True)

# Total number of stations
print('Total stations: '+str(len(stations.index)))

# Keep only stations which are current
current = stations['Last Year'] == 2019
print('Total current stations: '+str(len(stations[current])))

active_for_last_20 = stations['First Year'] < 2000
print('Total stations active before 2000: '+str(len(stations[active_for_last_20])))

st = stations[current & active_for_last_20]
print('Total current stations active for last 20 yrs: '+str(len(st)))

# Set up geometry
geometry = [Point(xy)
             for xy in  zip(
                 st['Longitude (Decimal Degrees)'],
                 st['Latitude (Decimal Degrees)']
             )
            ]
gdf = GeoDataFrame(st, geometry=geometry)

# Plot GeoDataFrame to Canada
world = gpd.read_file('World_Shapefile')
canada = world[world['SOVEREIGNT'] == 'Canada']
gdf.plot(
    ax=canada.plot(figsize=(10,10)), 
    marker='o', 
    color='orange', 
    markersize=5);

st.to_csv(root_path + 'Weather - Stations/current_station_inventory.csv.gz', index=False, compression='gzip')

"""Map current station to given coordinate system"""

# Read in grid data
grid = pd.read_csv(root_path + f'{province} Location/working_{province}_grid_system.csv.gz')

# Check data is read in
grid

from math import cos, asin, sqrt

def distance(lat1, lon1, lat2, lon2):
    p = 0.017453292519943295
    a = 0.5 - cos((lat2-lat1)*p)/2 + cos(lat1*p)*cos(lat2*p) * (1-cos((lon2-lon1)*p)) / 2
    return 12742 * asin(sqrt(a))

def closest(grid_location):
    st_dict = st.to_dict('records')
    closest_station = min(st_dict, key=lambda s: distance(
        grid_location['LATITUDE']+0.1,
        grid_location['LONGITUDE']+0.1,
        s['Latitude (Decimal Degrees)'],
        s['Longitude (Decimal Degrees)']))
    
    st_dict.remove(closest_station)
    second_closest_station = min(st_dict, key=lambda s: distance(
        grid_location['LATITUDE']+0.1,
        grid_location['LONGITUDE']+0.1,
        s['Latitude (Decimal Degrees)'],
        s['Longitude (Decimal Degrees)']))

    
    grid_location['STATION_ID'] = closest_station['Station ID']
    grid_location['STATION_LATITUDE'] = closest_station['Latitude (Decimal Degrees)']
    grid_location['STATION_LONGITUDE'] = closest_station['Longitude (Decimal Degrees)']
    grid_location['BACKUP_STATION_ID'] = second_closest_station['Station ID']
    return grid_location

# Go through grid
# For each grid location find closest weather station
# Append weather station to that grid location
grid = grid.apply(lambda row: closest(row), axis=1)

# Check that station ID column exists
grid.head()

# Set up grid geometry
def set_shape(row):
    x = row.LONGITUDE
    y = row.LATITUDE 
    x2 = row['STATION_LONGITUDE']
    y2 = row['STATION_LATITUDE']
    
    row['box'] = box(x,y,x+0.2, y+0.2) 
    row['line'] = LineString([(x+0.1,y+0.1), (x2,y2)])
    row['point'] = Point((x2,y2))
    
    return row
    
grid_with_shapes = grid.apply(lambda row: set_shape(row), axis=1)
point_gdf = GeoDataFrame(grid.copy(), geometry=grid_with_shapes['point'])
box_gdf = GeoDataFrame(grid.copy(), geometry=grid_with_shapes['box'])
line_gdf = GeoDataFrame(grid.copy(), geometry=grid_with_shapes['line'])

# Plot Canada, zoom in on Alberta
base = canada.plot(figsize=(10,10))
base.set_xlim(-123, -107.5) 
base.set_ylim(48, 61)

# Plot grid colors based on station ID
colors = plt.cm.plasma(np.linspace(0,1,box_gdf['STATION_ID'].nunique()))
color = iter(colors)
for name, group in box_gdf.groupby('STATION_ID'):
    base = group.plot(ax=base, edgecolor='white', color=next(color))

# Plot lines from each grid to closest weather station
base = line_gdf.plot(
    ax=base, 
    color='white',
    linewidth=0.3,
    label='Distance to grid')

# Plot weather station points
base = point_gdf.plot(
    ax=base,  
    color='red', 
    markersize=5,
    label='Weather stations');

base.set_xlabel('Latitude')
base.set_ylabel('Longitude')
base.set_title('Closest Weather Stations (Alberta)')
base.legend()

slim_grid = grid[['KEY','STATION_ID', 'BACKUP_STATION_ID']]
slim_grid.head()

slim_grid.to_csv(root_path + f'{province} Location/{province}_grid_system_with_station.csv.gz', index=False, compression='gzip')