# -*- coding: utf-8 -*-
"""2_tree_cover_script_c

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1plYvSv8MNRK-M2c6MPR6Kznlvei3r2UE
"""

import ee
import pandas as pd
from google.colab import files, drive
from tqdm import tqdm_notebook as tqdm

ee.Authenticate()
ee.Initialize()

# Mount Google Drive
drive.mount('/content/gdrive')
root_path = f'/content/gdrive/My Drive/Capstone Public Folder/Research - Tharmiga/Tree Cover/'

# Create new dataset for province w/ tree cover info
prov_array = ["BC","AL","SK","MB","ON","QB","NB","NS","PE","NL","YT","NT","NU"]
province = "NU"

df =  pd.read_csv(root_path + "Province Location Grid/" + province + "_location_grid.csv.gz", compression = 'gzip')
df = df.drop(['KEY','CENTROID'], axis='columns')
df['TREE_COVER_PERCENT'] = 0
df['PROVINCE'] = province

display(df.head())
print(len(df))

# Grab dataset from Google Earth Engine, filter for 2018 tree cover data
collection = ee.ImageCollection('MODIS/006/MOD44B')
collection = collection.filterDate('2018-01-01', '2018-12-31').select("Percent_Tree_Cover");

# Obtain one and only image from ImageCollection
image = ee.Image(collection.first()); 

# Convert null values (water) to 0
image = image.unmask(0);

# Loop and query API for each percentage value
for i in tqdm(range(len(df))):
  latitude = df.at[i, 'LATITUDE']
  longitude = df.at[i, 'LONGITUDE']
  rectangle = ee.Geometry.Rectangle([longitude,latitude,longitude+0.2,latitude+0.2]);
  data = image.reduceRegion(ee.Reducer.mean(),rectangle,30).get("Percent_Tree_Cover");
  value = ee.Number(data).getInfo()
  df.loc[[i], 'TREE_COVER_PERCENT'] = value

# Save as csv
display(df.head())
df.to_csv(root_path + "Province Tree Cover/" + province + "_tree_cover.csv.gz", compression= 'gzip', index = False)

