# -*- coding: utf-8 -*-
"""3_join_tree_cover_provinces.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QhE8ycdG4ggsQF1PagDHVhSmkHC4sIV6
"""

import pandas as pd
from google.colab import files, drive

# Mount Google Drive
drive.mount('/content/gdrive')
root_path = f'/content/gdrive/My Drive/Capstone Public Folder/Notebooks-DamageAlg/Tree Cover/'

# Combine csvs of location grid for all of Canada
full_df_columns = []
full_df_columns.append('LATITUDE')
full_df_columns.append('LONGITUDE')
full_df_columns.append('TREE_COVER_PERCENT')
full_df_columns.append('PROVINCE')
full_df = pd.DataFrame(columns=full_df_columns)

province_array = ["BC","AL","SK","MB","ON","QB","NB","NS","PE","NL","YT","NT"] # add nunavut!

for province in province_array:
  df =  pd.read_csv(root_path + "Province Tree Cover/" + province + "_tree_cover.csv.gz", compression = 'gzip')
  full_df = full_df.append(df, ignore_index=True)

full_df["LOCATION_KEY"] = full_df["LATITUDE"].astype(str) + "|" + full_df["LONGITUDE"].astype(str)
full_df = full_df.drop(columns=['PROVINCE'])
full_df = full_df.drop(columns=['LATITUDE'])
full_df = full_df.drop(columns=['LONGITUDE'])

print("Saving as CSV...")
full_df.to_csv(root_path + "Final Tree Cover CSV/final_tree_cover.csv.gz", compression= 'gzip', index = False)
display(full_df)
print("Done!")

# dataset = {"path": f"/content/gdrive/My Drive/Capstone Public Folder/Data/{province} Location/{province}_fire_location_grid.csv.gz"}
# df =  pd.read_csv("/content/gdrive/My Drive/Capstone Public Folder/Research - Tharmiga/Tree Cover/Province Location Grid/AL_location_grid.csv.gz", compression = 'gzip')
# df = df.drop(['KEY','CENTROID'], axis='columns')
# df['TREE_COVER_PERCENT'] = 0
# full_df = full_df.append(df, ignore_index=True)
  
# full_df = full_df.drop_duplicates()
# display(full_df)

# prov_array = ["BC","AL","SK","MB","ON","QB","NB","NS","PE","NL","YT","NT","NU"]
# province = "PE"

# for prov in prov_array:
#   df =  pd.read_csv(f"/content/gdrive/My Drive/Capstone Public Folder/Research - Tharmiga/Tree Cover/Province Location Grid/{province}_location_grid.csv.gz", compression = 'gzip')
#   df = df.drop(['KEY','CENTROID'], axis='columns')
#   df['TREE_COVER_PERCENT'] = 0
#   full_df = full_df.append(df, ignore_index=True)
# display(full_df)
# save as csv

